# Generated by Django 5.0.1 on 2024-01-14 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('link', models.CharField(blank=True, max_length=10000, null=True)),
                ('price', models.IntegerField()),
                ('total_uses', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('earn', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses_in_services', to='cost_calculator.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cost_calculator.service')),
            ],
            options={
                'verbose_name': 'Producto para un Servicio',
                'verbose_name_plural': 'Productos para un Servicio',
            },
        ),
    ]
